addSbtPlugin("org.scala-js"              % "sbt-scalajs"  % "1.14.0")
addSbtPlugin("io.indigoengine"          %% "sbt-indigo"   % "0.15.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.4.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix" % "0.9.31")
addSbtPlugin("com.github.reibitto"       % "sbt-welcome"  % "0.3.1")
