addSbtPlugin("org.scala-js"             %% "sbt-scalajs"        % "1.11.0")
addSbtPlugin("io.indigoengine"          %% "sbt-indigo"         % "0.14.0")
addSbtPlugin("org.xerial.sbt"           %% "sbt-sonatype"       % "3.9.7")
addSbtPlugin("com.jsuereth"             %% "sbt-pgp"            % "2.0.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"       % "0.3.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"       % "0.9.31")
addSbtPlugin("com.github.reibitto"       % "sbt-welcome"        % "0.2.2")
