addSbtPlugin("org.scala-js"        % "sbt-scalajs"  % "1.19.0")
addSbtPlugin("io.indigoengine"    %% "sbt-indigo"   % "0.19.0")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt" % "2.5.4")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix" % "0.14.0")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"  % "0.5.0")
