name: CI
on: [workflow_dispatch, push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v11
      with:
        java-version: adopt@1.11
    - name: Compile & Test
      run: bash build.sh
